name: custom-cms
recipe: lamp
config:
  webroot: .
  database: mysql:8.0.27
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  phpmyadmin:
    - phpmyadmin.ecom.lndo.site
