services:
  demo.service:
    class: \Cms\Services\ServicesClass\DemoService
  
  current_date.service:
    class: \Cms\Services\ServicesClass\DateService
  
  message.service: {
    class: \Cms\Services\ServicesClass\MessageGenerator
  }
